general {
        output_format = "i3bar"
        colors = true
        interval = 5
        color_bad = "#e01010"
        #color_good = "#808080"
        color_good = "#ffffff"
        color_degraded = "#606060"
}

order += "ipv6"
order += "wireless wlan0"
# order += "ethernet eth0"
order += "battery 0"
order += "cpu_temperature 0"
order += "volume master"
order += "time"

ipv6 {
        format_up = "%ip"
        format_down = ""
}

wireless wlan0 {
        format_up = " WiFi: (%quality at %essid, %bitrate) %ip "
        format_down = ""
}

ethernet eth0 {
        format_up = " %ip "
        format_down = " eth0: down "
}

battery 0 {
        format = "%status %percentage %remaining %emptytime"
        format_down = ""
        path = "/sys/class/power_supply/BAT%d/uevent"
        low_threshold = 10
}

time {
        format = " %d.%m %H:%M"
}

volume master {
        format = "⟨ %volume ⟩"
        format_muted = "⟨ %volume ⟩"
        device = "default"
        mixer = "Master"
        mixer_idx = 0
}

cpu_temperature 0 {
        format = " %degrees °C "
        path = "/sys/bus/platform/devices/coretemp.0/hwmon/hwmon0/temp2_input"
}
